# Global 全局配置
site_analytics: ''
hoster: <a href="https://github.io" target="_blank">Github Pages</a>
site_logo: ''
snow: false
click_animate_js: false
enable_dark: true
highlight_theme: night-eighties # 代码高亮主题（light | night | night-eighties | night-blue | night-bright）
check_update: false
# canonical: true

vendors:
  packages:
    disqusjs: 
      version: 1.2.6
    gitalk: 
      version: 1.7.2
    gitment: 
      version: 0.0.3
    twikoo: 
      version: 1.5.11
    valine: 
      version: 1.4.18
    "@waline/client": 
      version: 2.14.1
    bootstrap: 
      version: 3.3.4
    nprogress: 
      version: 0.2.0
    aplayer: 
      version: 1.10.1
    "@fancyapps/fancybox": 
      version: 3.5.7
    layui-src: 
      version: 2.5.5
    font-awesome: 
      version: 4.7.0
    jquery: 
      version: 3.6.0
    qrcode_js: 
      version: 1.0.0
    mermaid: 
      version: 9.1.1
    meting:
      version: 2.0.1

# 自定义样式
customStyles:
  images: # 图片相关设置
    banner: https://github.com/sablin39/sablin39.github.io/theme_assets/1131709.jpg # 站点横幅
    # background: /images/bg.webp # 站点背景

# Index 首页配置
index:
  post_type: false
  read_count: true
  comment_count: true

# Top Menu 顶部导航栏配置 （具体格式请参照文档）
menu:
  index: /
  #archives: /archives/
  categories: /categories/
  # workshops:
  #   submenu: true
  #   #fire-control: 
  #   fin-sta: /categories/NeRF/
  friends: /friends/
  sites:
    submenu: true
    mtf: https://mtf.wiki/
    ftm: https://ftm.wiki/
    hrt: https://docs.hrt.guide/
    tfsci: https://tfsci.mtf.wiki/
    en_tsci: https://transfemscience.org/
    game: https://taylormccue.itch.io/do-i-pass
    
    



label:
  index: <i class="fa fa-home"></i>Home
  #archives: <i class="fa fa-file"></i>档案馆
  categories: <i class="fa fa-file"></i>Contents
  # workshops: 
  #   submenu: <i class="fa-solid fa-screwdriver-wrench"></i>Workshops
  #   #fire-control: 
  #   fin-sta: NeRF
  friends: <i class="fa fa-paw"></i>Pals
  sites:
    submenu: Trans Guides
    mtf: MtF Wiki
    ftm: FtM Wiki
    hrt: Shizu's HRT guide
    tfsci: 女性倾向跨性别者科学
    en_tsci: Transfeminine Science
    game: A little game :)
# Footer 页脚配置
group_link: 
contact: # 出于兼容性考虑，继续保留
  weibo: 
  mail: 
  telegram:
  twitter: 
  facebook: 
  linkedin: 
  fediverse:
    instance:
    username:
  github:
  rss:
footerLinks: [] # 可以自定义
timenotice: 本站已运行
icp: 
psr:
  
# Post Page 文章页配置
posts:
  show_cc: true
  donate: false
  share: true
  comments: 
    provider: ''
    enableBGImage: false
  wordCount: 
    enable: true
    threshold: 1500

# Disqus [Disqus](https://disqus.com) 评论相关
disqus:
  shortname: 

# DisqusJS [DisqusJS](https://disqusjs.skk.moe/) 评论相关
disqusjs:
  shortname: 
  sitename: 
  api: 
  apikey: 
  admin: 
  adminlabel: 

# Valine [Valine](https://valine.js.org) 评论相关
valine:
  app_id: 
  app_key: 
  visitor: true
  enableQQ: false

# Twikoo [Twikoo](https://twikoo.js.org) 评论相关
twikoo:
  env_id: 

# Waline [Waline](https://waline.js.org) 评论相关
## 不仅限于以下内容，您可以参照 Waline的 [前端配置文档](https://waline.js.org/reference/client.html) 设置您需要的配置项
## el 和 path 会在页面自动生成，不必加入
waline:
  serverURL: #后端服务器地址，必填
  comment: true
  pageview: true

# Gitalk [Gitalk](https://gitalk.github.io/) 评论相关
## 不仅限于以下内容，您可以参照 [Gitalk 文档](https://github.com/gitalk/gitalk/blob/master/readme-cn.md#%E8%AE%BE%E7%BD%AE) 设置您需要的配置项
## id 会在页面自动生成，不必加入
gitalk:
  clientID: 'GitHub Application Client ID'
  clientSecret: 'GitHub Application Client Secret'
  repo: 'Kratos-Rebirth-Demo'
  owner: 'Candinya'
  admin: 
    - 'Candinya'
  distractionFreeMode: false

#默认不计算hash 但是如果id过长(默认为url_for(page.path))会导致创建评论区失败 见[#139](https://github.com/Candinya/Kratos-Rebirth/issues/139)
gitalk_id_hasher: false
# gitalk_id_hasher: md5

# Gitment [Gitment](https://github.com/imsun/gitment/) 评论相关
## 不仅限于以下内容，您可以参照 [Gitment 文档](https://github.com/imsun/gitment#methods) 设置您需要的配置项
## id 会在页面自动生成，不必加入
gitment:
  owner: 'Candinya'
  repo: 'Kratos-Rebirth-Demo'
  oauth:
    client_id: 'Your client ID'
    client_secret: 'Your client secret'

# LiveRe [LiveRe](https://livere.com/) 评论相关
livere:
  id: city
  uid:

# APlayer 左下角音乐播放器
aplayer:
  enabled: false
  playlist: 
  meting:
    server: netease
    type: playlist
    id: 3204190542
  order: random

# Widgets 侧边栏小挂件
sidebar: right
widgets:
- about
- splitter
- toc
- category
- tagcloud
- posts
avatarUri: https://github.com/sablin39.png
mobile_toc: 
  hide: false
  hide_id: false

# Fancybox 文章内图片单击放大
fancybox: true

# Search 搜索
search:
  enable: true
  path: search.json
  field: post # page | post | all. Default post
  content: true # Include post | page content

# JavaScript 相关配置
## 由于Javascript被压缩后难以有效编辑与生成，因而为了简化操作，将相关的配置项在生成文件时以独立的json文件写出，调用时使用fetch API获取。
jsconfig:
  main:
    cover:
      randomAmount: 20 # 表示从1~20
      baseUrl: null # 使用默认值（不单独配置），将跟随 vendors 中的相关设定选择是否使用 cdn
      filenameTemplate: "thumb_{no}.webp" 
    createTime: "2022/6/4 00:00:01"
    donateBtn: "支持我~"
    scanNotice: "扫一扫，好不好？"
    qr_alipay: "/images/alipayqr.webp"
    qr_wechat: "/images/wechatpayqr.webp"
    siteLeaveEvent: false
    leaveTitle: "{{{(>_<)}}}哦哟，崩溃啦~"
    returnTitle: "(*´∇｀*)欸，又好啦~"
    copyrightNotice: "该内容采用 CC BY-NC-SA 4.0 许可协议，著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。"
    expire_day: false
    topNavScrollToggle: true

# Site verify 站点验证相关配置内容
site_verify:
  google: 
  baidu: 
  bing: 

# Friends 友链相关内容
friends:
  href: "friends"
  page:
    title: "My Supportive Friends"
    comments: true
    description: "Thanks for meeting you guys :)"
    updated: "2024-04-06"
  list:
  - name: "TingNote"
    bio: "喵~"
    avatar: "../images/ting.png"
    link: "https://www.cnblogs.com/tingnote/"
  - name: "欢迎来看红光今天吃什么"
    bio: "喵~"
    avatar: "../images/Patchouli.jpg"
    link: "https://redlightasl.top/"
  - name: "Beiyan Da(北雁 达)"
    bio: "醉里不知天在水，满船清梦压星河。"
    avatar: "https://da.beiyan.us/assets/littleyushi.jpg"
    link: "https://da.beiyan.us/"
  - name: "木头人的小木屋"
    bio: "人生南北多歧路，时代喧哗造物忙。"
    avatar: "https://woodman3.github.io/img/avatar_huc17459e21dbc94a20608b5fd196ea845_3679_300x0_resize_q75_box.jpg"
    link: "https://woodman3.github.io/"
    
  #   bio: "咪啪~"
  #   avatar: "../images/avatar.webp"
  #   link: "https://candinya.com"
  verify: true # 验证每个友链的可访问性，炸了会有提示

# Misc 杂项
misc:
  showWordCountEstimateWavy: true # 在文章字数处显示表示大约字数的波浪号